# ARRAYS

In [1]:
import array as arr

In [2]:
a=arr.array('i',[3,4,5,])     #creating an array a

In [3]:
a

array('i', [3, 4, 5])

In [4]:
b=arr.array('i',[4,8,9])

In [5]:
b

array('i', [4, 8, 9])

# SLICING

In [6]:
a[2:]    #slicing

array('i', [5])

In [7]:
a[::-1]            #reverse

array('i', [5, 4, 3])

In [8]:
a.append(8)

In [9]:
a

array('i', [3, 4, 5, 8])

In [10]:
a.pop()

8

In [11]:
a.pop(1)
a

array('i', [3, 5])

In [15]:
a.remove(5)
a

array('i', [3])

In [16]:
for i in a:
    print(i,end="")
    

3

In [17]:
a+b        #concatenation

array('i', [3, 4, 8, 9])

# NUMPY

`pip install numpy

In [19]:
import numpy as np

In [21]:
k=np.array([(4,5,6),(6,7,8)])
m=np.array([(2,3,5),(1,3,6)])
k

array([[4, 5, 6],
       [6, 7, 8]])

In [23]:
m

array([[2, 3, 5],
       [1, 3, 6]])

In [24]:
m.ndim        #to check the dimensions

2

In [26]:
m.itemsize  #to know the size of each element

4

In [27]:
k.dtype

dtype('int32')

In [28]:
m.shape

(2, 3)

In [29]:
k.reshape(3,2)

array([[4, 5],
       [6, 6],
       [7, 8]])

In [30]:
m.size

6

In [31]:
m.min

<function ndarray.min>

In [32]:
m.min(1)

array([2, 1])

In [33]:
m.min()

1

In [34]:
m.max()

6

In [35]:
m.sum()

20

In [36]:
g=np.linspace(1,8,15)
g


array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. ])

In [37]:
m.sum(axis=0)           #coloum wise

array([ 3,  6, 11])

In [39]:
m.sum(axis=1)           #row wise

array([10, 10])

In [40]:
np.sqrt(m)

array([[1.41421356, 1.73205081, 2.23606798],
       [1.        , 1.73205081, 2.44948974]])

In [41]:
np.std(m)

1.699673171197595

In [42]:
np.mean(k)

6.0

In [44]:
k

array([[4, 5, 6],
       [6, 7, 8]])

In [46]:
k[0,2]               # zeroth row 2nd element

6

In [47]:
k[0:2,1]                   #zeroth row first row 

array([5, 7])

In [48]:
k[1,2]

8

In [49]:
k[k>2]                       

array([4, 5, 6, 6, 7, 8])

In [50]:
m[m<=2]

array([2, 1])

In [52]:
k.sort()
k

array([[4, 5, 6],
       [6, 7, 8]])

In [53]:
k+m

array([[ 6,  8, 11],
       [ 7, 10, 14]])

In [54]:
k%m

array([[0, 2, 1],
       [0, 1, 2]], dtype=int32)